### ISSUE TITLE
Run location

### ISSUE THREAD

**Issue by delofson0211** [Q-Pix/qpixrec#9]
It appears that the run_analysis.py file can only be run from within the lightless_reconstruction directory, otherwise it can't find the other scripts that it calls. Can we change it so it detects where the file is (maybe take the base argument of the file itself to find the directory), and uses that directory to locate the other scripts that are called?

**Comment by Eikenbcr** [comment]
I can look into that. This should only require a minor addition to the run_analysis.py script.
